const data = [
    {
      "item_id": 24,
      "item_group": "Finished Product (FP)",
      "packing_applicable": 1,
      "item_category": "",
      "part_number": "10624",
      "cas_number": "123333-53-9",
      "item_name": "1-Hydroxybenzotriazole Monohydrate",
      "alternate_name": "1-HOBT Monohydrate",
      "identifying_character": "H",
      "uom": "KILOGRAM",
      "alternate_uom": "GRAM",
      "relation": "1000",
      "physical_state": "Solid",
      "molecular_formula": "C<sub>6</sub>H<sub>7</sub>N<sub>3</sub>O<sub>2</sub>",
      "molecular_weight": "153.12",
      "gst_rate": "18",
      "gst_applicable": 1,
      "storage_condition": "At Ambient Temperature<span style=\"white-space:pre\">\t</span>",
      "hsn_code": "29331990",
      "packing_material": "",
      "packing_group": "I",
      "un_number": "3474",
      "qc_applicable": 1,
      "scale_of_synthesis": "Commercial Scale",
      "hazards_class": "4.1",
      "structure_image": "123333-53-92021-11-25120307.jpg",
      "msds_attachment": "123333-53-9_msds_2021-11-25120307.pdf",
      "is_controlled_product": 0,
      "application": "<p>Coupling Reagent</p>\r\n",
      "safety_symbol1": "",
      "safety_symbol2": "",
      "safety_symbol3": "",
      "status": "Active",
      "creation_date": "2021-11-20T06:50:01.000Z",
      "last_update_date": "2021-11-25T06:33:07.000Z"
    },
    {
      "item_id": 29,
      "item_group": "Finished Product (FP)",
      "packing_applicable": 1,
      "item_category": "",
      "part_number": "10199",
      "cas_number": "25952-53-8",
      "item_name": "N-(3-Dimethylaminopropyl)-3-Ethylcarbodimide HCl",
      "alternate_name": "EDCI HCl",
      "identifying_character": "D",
      "uom": "KILOGRAM",
      "alternate_uom": "GRAM",
      "relation": "1000",
      "physical_state": "Solid",
      "molecular_formula": "C<sub>8</sub>H<sub>18</sub>ClN<sub>3</sub>",
      "molecular_weight": "191.70",
      "gst_rate": "18",
      "gst_applicable": 1,
      "storage_condition": "NMT 25<sup>o</sup>C under inert conditions",
      "hsn_code": "29251900",
      "packing_material": "HMHDE DRUMS",
      "packing_group": "",
      "un_number": "",
      "qc_applicable": 1,
      "scale_of_synthesis": "Commercial Scale",
      "hazards_class": "hazards",
      "structure_image": "25952-53-82021-11-25120521.jpg",
      "msds_attachment": "25952-53-8_msds_2021-11-25120521.pdf",
      "is_controlled_product": 0,
      "application": "<p>Coupling Reagent. Used in Atazanavir, Sitagliptin,&nbsp;Mirabegron</p>\r\n",
      "safety_symbol1": "",
      "safety_symbol2": "",
      "safety_symbol3": "",
      "status": "Active",
      "creation_date": "2021-11-20T12:27:26.000Z",
      "last_update_date": "2021-12-11T10:09:23.000Z"
    },
    {
      "item_id": 30,
      "item_group": "Finished Product (FP)",
      "packing_applicable": 1,
      "item_category": "",
      "part_number": "11076",
      "cas_number": "6640-22-8",
      "item_name": "di-Sodium Pamoate",
      "alternate_name": "",
      "identifying_character": "S",
      "uom": "KILOGRAM",
      "alternate_uom": "GRAM",
      "relation": "1000",
      "physical_state": "Solid",
      "molecular_formula": "C<sub>23</sub>H<sub>14</sub>Na<sub>2</sub>O<sub>6</sub>",
      "molecular_weight": "432.33",
      "gst_rate": "18",
      "gst_applicable": 1,
      "storage_condition": "At Ambient Temperature",
      "hsn_code": "29420090",
      "packing_material": "",
      "packing_group": "",
      "un_number": "",
      "qc_applicable": 1,
      "scale_of_synthesis": "Commercial Scale",
      "hazards_class": "",
      "structure_image": "6640-22-82021-11-25121759.png",
      "msds_attachment": "6640-22-8_msds_2021-11-25121759.pdf",
      "is_controlled_product": 0,
      "application": "<p>Used in Pyrantel Pamoate</p>\r\n",
      "safety_symbol1": "",
      "safety_symbol2": "",
      "safety_symbol3": "",
      "status": "Active",
      "creation_date": "2021-11-25T06:48:00.000Z",
      "last_update_date": null
    },
    {
      "item_id": 31,
      "item_group": "Finished Product (FP)",
      "packing_applicable": 1,
      "item_category": "",
      "part_number": "11085",
      "cas_number": "7697-37-2",
      "item_name": "Nitric Acid ",
      "alternate_name": "",
      "identifying_character": "N",
      "uom": "KILOGRAM",
      "alternate_uom": "",
      "relation": "",
      "physical_state": "Liquid",
      "molecular_formula": "HNO<sub>3</sub>",
      "molecular_weight": "63.01",
      "gst_rate": "18",
      "gst_applicable": 1,
      "storage_condition": "Store in well closed container, at ambient temperature<span style=\"white-space:pre\">\t</span>",
      "hsn_code": "28080010",
      "packing_material": "",
      "packing_group": "II",
      "un_number": "2031",
      "qc_applicable": 1,
      "scale_of_synthesis": "",
      "hazards_class": "8",
      "structure_image": "nitricacid2021-11-25184644.png",
      "msds_attachment": "",
      "is_controlled_product": 0,
      "application": "",
      "safety_symbol1": "",
      "safety_symbol2": "",
      "safety_symbol3": "",
      "status": "Active",
      "creation_date": "2021-11-25T13:12:30.000Z",
      "last_update_date": "2021-11-25T13:18:10.000Z"
    },
    {
      "item_id": 32,
      "item_group": "Finished Product (FP)",
      "packing_applicable": 1,
      "item_category": "",
      "part_number": "10637",
      "cas_number": "60-00-4",
      "item_name": "EDTA",
      "alternate_name": "",
      "identifying_character": "E",
      "uom": "KILOGRAM",
      "alternate_uom": "GRAM",
      "relation": "1000",
      "physical_state": "Solid",
      "molecular_formula": "C<sub>10</sub>H<sub>16</sub>N<sub>2</sub>O<sub>8</sub>",
      "molecular_weight": "292.24",
      "gst_rate": "18",
      "gst_applicable": 1,
      "storage_condition": "Store in Airtight Drum, at ambient temperature",
      "hsn_code": "29224990",
      "packing_material": "",
      "packing_group": "",
      "un_number": "",
      "qc_applicable": 1,
      "scale_of_synthesis": "None",
      "hazards_class": "",
      "structure_image": "60-00-42021-12-23171754.png",
      "msds_attachment": "",
      "is_controlled_product": 0,
      "application": "",
      "safety_symbol1": "",
      "safety_symbol2": "",
      "safety_symbol3": "",
      "status": "Active",
      "creation_date": "2021-12-03T13:14:51.000Z",
      "last_update_date": "2021-12-23T11:47:54.000Z"
    },
    {
      "item_id": 37,
      "item_group": "Finished Product (FP)",
      "packing_applicable": 1,
      "item_category": "",
      "part_number": "10894",
      "cas_number": "524-38-9",
      "item_name": "N-Hydroxyphthalimide",
      "alternate_name": "",
      "identifying_character": "H",
      "uom": "KILOGRAM",
      "alternate_uom": "GRAM",
      "relation": "1000",
      "physical_state": "Solid",
      "molecular_formula": "C<sub>8</sub>H<sub>5</sub>NO<sub>3</sub>",
      "molecular_weight": "163.13",
      "gst_rate": "18",
      "gst_applicable": 1,
      "storage_condition": "Well Closed, Air Tight containers and store at Room Temperature",
      "hsn_code": "29251900",
      "packing_material": "",
      "packing_group": "",
      "un_number": "",
      "qc_applicable": 1,
      "scale_of_synthesis": "Commercial Scale",
      "hazards_class": "",
      "structure_image": "524-38-92021-12-04103052.jpg",
      "msds_attachment": "524-38-9_msds_2021-12-04103052.pdf",
      "is_controlled_product": 0,
      "application": "<p>It is used as Catalyst for Oxidation Reactions.</p>\r\n",
      "safety_symbol1": "PQR",
      "safety_symbol2": "",
      "safety_symbol3": "",
      "status": "Active",
      "creation_date": "2021-12-04T05:00:53.000Z",
      "last_update_date": null
    }
]

export default data;